---

- include: packages.yml

- hosts: localhost
  become: false
  connection: local
  vars:
    sac_file_path: "{{ lookup('env','HOME') }}/Downloads/SAC_9_1_Linux.zip"
    tmp_path: /tmp/SAC_9_1_Linux

  tasks:

    - name: unarchive downloaded zip
      command: unzip "{{ sac_file_path }}"
      args:
        chdir: /tmp/
        creates: "{{ tmp_path }}"
      tags:
        - unarchive

    - name: import GPG key
      become: true
      rpm_key:
        state: present
        key: "{{ tmp_path }}/Installation/Core/RPM/RPM-GPG-KEY-SafenetAuthenticationClient"
      tags:
        - import

    - name: install packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_fileglob:
        - "{{ tmp_path }}/Installation/Standard/RPM/SafenetAuthenticationClient-*.{{ ansible_architecture }}.rpm"
        - "{{ tmp_path }}/Installation/Core/RPM/SafenetAuthenticationClient-core-*.{{ ansible_architecture }}.rpm"
        - "{{ tmp_path }}/Installation/x32 Compatibility/RPM/SAC-32-CompatibilityPack-*.x86_64.rpm"
      tags:
        - rpms
